"""NyxOS Markdown Exporter — Findings to clean Markdown."""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

from loguru import logger

_SEVERITY_LABELS = {
    "critical": "CRITICAL",
    "high": "HIGH",
    "medium": "MEDIUM",
    "low": "LOW",
    "info": "INFO",
}


class MarkdownExporter:
    """Exports report data to a clean Markdown file."""

    def export(self, report_data: Dict[str, Any], output_path: str) -> str:
        """Generate Markdown report and write to disk. Returns file path."""
        output = Path(output_path).expanduser().resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        md = self._build_markdown(report_data)
        output.write_text(md, encoding="utf-8")
        logger.info("Markdown report -> {} ({} chars)", output, len(md))
        return str(output)

    def _build_markdown(self, data: Dict[str, Any]) -> str:
        s: List[str] = []
        target = data.get("target", "Unknown Target")
        rt = data.get("report_type_display", data.get("report_type", "Security Assessment"))
        date = data.get("date", "")
        author = data.get("author", "NyxOS Operator")
        ver = data.get("nyxos_version", "0.1.0")
        proj = data.get("project_name", "default")

        s.append(f"# {rt} Report: {target}\n")
        s.append(f"> **Generated by NyxOS** v{ver}  ")
        s.append(f"> **Date:** {date}  ")
        s.append(f"> **Author:** {author}  ")
        s.append(f"> **Project:** {proj}\n")
        s.append("---\n")

        s.append("## Executive Summary\n")
        s.append(data.get("executive_summary", "No summary available.") + "\n")

        rs = data.get("risk_score", {})
        s.append("## Risk Assessment\n")
        s.append(f"**Score: {rs.get('score', 0.0)} / 10.0 — {rs.get('level', 'NONE')}**\n")
        bd = rs.get("breakdown", {})
        if bd:
            s.append("| Severity | Count |")
            s.append("|----------|-------|")
            for sv in ("critical", "high", "medium", "low", "info"):
                s.append(f"| {_SEVERITY_LABELS.get(sv, sv.upper())} | {bd.get(sv, 0)} |")
            s.append("")

        findings = data.get("findings", [])
        s.append("## Findings Overview\n")
        if not findings:
            s.append("*No findings identified.*\n")
        else:
            s.append(f"**Total: {len(findings)}**\n")
            s.append("| # | Severity | Title | Type |")
            s.append("|---|----------|-------|------|")
            for i, f in enumerate(findings, 1):
                sv = _SEVERITY_LABELS.get(f.get("severity", "info").lower(), "INFO")
                s.append(f"| {i} | {sv} | {f.get('title', 'Untitled')} | {f.get('type', 'unknown')} |")
            s.append("")

        s.append("## Detailed Findings\n")
        if not findings:
            s.append("*No detailed findings.*\n")
        else:
            for i, f in enumerate(findings, 1):
                sv = f.get("severity", "info")
                lbl = _SEVERITY_LABELS.get(sv.lower(), sv.upper())
                s.append(f"### {i}. [{lbl}] {f.get('title', 'Untitled')}\n")
                s.append(f"**Severity:** {sv.upper()}  ")
                s.append(f"**Type:** {f.get('type', 'unknown')}  ")
                if f.get("tool_used"):
                    s.append(f"**Tool:** {f['tool_used']}  ")
                if f.get("url"):
                    s.append(f"**URL:** `{f['url']}`  ")
                s.append("")
                narr = f.get("narrative", f.get("description", "No description."))
                s.append(f"{narr}\n")
                if f.get("evidence"):
                    s.append(f"**Evidence:**\n```\n{f['evidence']}\n```\n")
                if f.get("recommendation"):
                    s.append(f"**Recommendation:** {f['recommendation']}\n")
                s.append("---\n")

        s.append("## Remediation Recommendations\n")
        s.append(data.get("remediation", "No recommendations.") + "\n")

        s.append("## Appendix\n")
        tl = data.get("commands_timeline", [])
        if tl:
            s.append("| Timestamp | Command | Result |")
            s.append("|-----------|---------|--------|")
            for e in tl:
                cmd = e.get("command", "").replace("|", "\\|")
                res = e.get("result", "")[:100].replace("|", "\\|")
                s.append(f"| {e.get('timestamp', '')} | `{cmd}` | {res} |")
            s.append("")
        else:
            s.append("*No timeline data.*\n")

        s.append("---\n")
        s.append(f"*Generated by NyxOS v{ver} — {date}.*\n")
        return "\n".join(s)
